[programs.devnet]
mygifcollection = "BFqDFPmjujd3mgmkP3hMU7qXqVmhqN5fNorRMbBSzuk4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/mehul/.config/solana/id.json"

[scripts]
test = "node tests/mygifcollection.js"
